### ISSUE TITLE
Tournament Integration

### ISSUE THREAD

**Issue by jedigeiss** [jedigeiss/MonsterDiscordBot#4]
as stated within the Idea post for Utopian [here](https://steemit.com/utopian-io/@rivalzzz/monsterbot-steemmonsters-tournaments-integration-b9f34f268cf1fest) the bot should also integrate the possibility to display upcoming tournaments and information related to that

**Comment by RivalzZz88** [comment]
Yep, i will add the upcoming issues by myself.

**Comment by jedigeiss** [comment]
integration of tournaments has been added and pushed to production
